version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: data_pipeline_prototype/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ../risk:/app/risk
    command: uvicorn api.app:app --host 0.0.0.0 --port 8080 --reload
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
